import express from "express";
import { ref, set, get } from "firebase/database";
import { collection, addDoc, Timestamp } from "firebase/firestore";
import { database } from "../firebase-config.js";

const router = express.Router();

/* schema for conversation */
/* 
{
    id: string [generated by firebase],
    member: [
        user1: string,
        user2: string
    ],
    createAt: date,
    updateAt: date
}

*/


/* for create a new conversation */
/* path for conversation  */
router.post('/', async (req,res) => {

    try {
        const newConversation = await addDoc(collection(database, "conversation"), {
            member: [
                req.body.senderId,
                req.body.receiverId
            ],
            createAt: new Date(),
            updateAt: new Date()
        });
        console.log("Document written with ID: ", newConversation.id);
        res.status(200).json({message : "successfull add a new conversation"})
    }
    catch (err){
        console.error("Error adding document: ", err);
    }
})


export default router